apiVersion: v1
kind: Service
metadata:
  name: locust-service
  namespace: locust-load-test
spec:
  selector:
    app: locust
  ports:
  - name: web
    protocol: TCP
    port: 8089
    targetPort: 8089
  - name: p2p-1
    protocol: TCP
    port: 5557
    targetPort: 5557
  - name: p2p-2
    protocol: TCP
    port: 5558
    targetPort: 5558
