apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: locust-load-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        resources:
          limits:
            memory: "256Mi"  # Batasan maksimum penggunaan memori
            cpu: "500m"       # Batasan maksimum penggunaan CPU
          requests:
            memory: "128Mi"  # Permintaan minimum memori
            cpu: "250m"      # Permintaan minimum CPU
        args: ["-f", "/mnt/locust/locustfile.py", "--host=http://nodeapp.hibban.my.id:80"]
        volumeMounts:
        - name: locust-script
          mountPath: /mnt/locust
        ports:
        - containerPort: 8089
        - containerPort: 5557
        - containerPort: 5558
      restartPolicy: Always
      volumes:
      - name: locust-script
        configMap:
          name: locust-script
